export const topicsData = [
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Blockchain Technology", label: "Blockchain Technology" },
  { value: "Climate Change", label: "Climate Change" },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "E-commerce Trends", label: "E-commerce Trends" },
  { value: "Fashion Industry", label: "Fashion Industry" },
  { value: "Global Health Challenges", label: "Global Health Challenges" },
  { value: "Human Rights Issues", label: "Human Rights Issues" },
  { value: "Internet of Things (IoT)", label: "Internet of Things (IoT)" },
  { value: "Machine Learning", label: "Machine Learning" },
  { value: "Natural Language Processing", label: "Natural Language Processing" },
  { value: "Online Privacy", label: "Online Privacy" },
  { value: "Quantum Computing", label: "Quantum Computing" },
  { value: "Renewable Energy Sources", label: "Renewable Energy Sources" },
  { value: "Space Exploration", label: "Space Exploration" },
  { value: "Technology Ethics", label: "Technology Ethics" },
  { value: "Urbanization Challenges", label: "Urbanization Challenges" },
  { value: "Virtual Reality (VR)", label: "Virtual Reality (VR)" },
  { value: "Women's Empowerment", label: "Women's Empowerment" },
  { value: "Youth Mental Health", label: "Youth Mental Health" },
];

export const coursesData = [
  { value: "Mathematics", label: "Mathematics" },
  { value: "Physics", label: "Physics" },
  { value: "Chemistry", label: "Chemistry" },
  { value: "Biology", label: "Biology" },
  { value: "History", label: "History" },
  { value: "Literature", label: "Literature" },
  { value: "Geography", label: "Geography" },
  { value: "Computer Science", label: "Computer Science" },
  { value: "Economics", label: "Economics" },
  { value: "Political Science", label: "Political Science" },
  { value: "Psychology", label: "Psychology" },
  { value: "Sociology", label: "Sociology" },
  { value: "Environmental Science", label: "Environmental Science" },
  { value: "Philosophy", label: "Philosophy" },
  { value: "Languages", label: "Languages" },
  { value: "Business Studies", label: "Business Studies" },
  { value: "Media Studies", label: "Media Studies" },
  { value: "Health Sciences", label: "Health Sciences" },
  { value: "Engineering", label: "Engineering" },
  { value: "Fine Arts", label: "Fine Arts" },
];
